Repository/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse_lazy
from django.views.i18n import JavaScriptCatalog
from django_js_reverse.views import urls_js
from django.views.decorators.cache import cache_page
from django.utils.translation import ugettext_lazy as _
from django.conf.urls.i18n import i18n_patterns
from django.views.static import serve

import settings

js_info_dict = {
	'app_names': ('Repository.manager',),
}

urlpatterns = i18n_patterns(
	url(r'^$', RedirectView.as_view(url=reverse_lazy('manager:home'), permanent=False), name='home'),
	url(_(r'^manager/'), include('manager.urls', namespace="manager", app_name="manager"), name='manager'),
	url(_(r'^authentication/'), include('authentication.urls', namespace="authentication", app_name="authentication"), name='authentication'),
	url(_(r'^submission/'), include('submission.urls', namespace="submission", app_name="submission"), name='submission'),
	url(_(r'^inbox/'), include('inbox.urls', namespace="inbox", app_name="inbox"), name='inbox'),

	url(_(r'^about$'), TemplateView.as_view(template_name="base/about.html"), name="about"),
	url(_(r'^terms$'), TemplateView.as_view(template_name="base/terms.html"), name="terms"),
	url(_(r'^policies$'), TemplateView.as_view(template_name="base/policies.html"), name="policies"),
	url(_(r'^contact_us$'), TemplateView.as_view(template_name="base/contact_us.html"), name="contact_us"),
		
	url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,}),
	url(r'^i18n/', include('django.conf.urls.i18n')),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^rosetta/', include('rosetta.urls')),
	url(r'^jsreverse/$', cache_page(3600)(urls_js), name='js_reverse'),
	url(r'^jsi18n/$', JavaScriptCatalog.as_view(packages=['base', 'authentication', 'manager', 'submission', 'inbox', ]), name='javascript-catalog'),
)

manager/models/publication.py
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse_lazy
from django.db import models
import itertools

class Publication(models.Model):
	TYPOLOGY_CHOICES = (
		(u'article', _(u'Article')),
		(u'book', _(u'Book')),
		(u'booklet', _(u'Booklet')),
		(u'conference', _(u'Conference')),
		(u'inbook', _(u'Inbook')),
		(u'incollection', _(u'Incollection')),
		(u'manual', _(u'Manual')),
		(u'mastersthesis', _(u'Masters Thesis')),
		(u'monography', _(u'Monography')),
		(u'dissertation', _(u'Dissertation')),
		(u'abstract', _(u'Abstract')),
	)
	LANGUAGE_CHOICES = (
		(u'pt_BR', _(u'Brazilian Portuguese')),
		(u'en', _(u'English')),
		(u'es', _(u'Spanish')),
	)
	title = models.CharField(verbose_name=_("Title"), max_length=500, null=False, blank=False)
	slug = models.SlugField(_('slug'), max_length=1000, blank=True, unique=True)
	typology = models.CharField(verbose_name=_("Typology"), choices=TYPOLOGY_CHOICES, max_length=100, null=False, blank=False)
	subjects = models.ManyToManyField("Subject", verbose_name=_("Subjects"), blank=False)
	authors = models.ManyToManyField("Author", verbose_name=_("Authors"), related_name="Authors", blank=False)
	community = models.ForeignKey("Community", verbose_name=_("Community"), null=False, blank=False)
	collection = models.ForeignKey("Collection", verbose_name=_("Collection"), null=False, blank=False)
	publisher = models.ForeignKey("Publisher", verbose_name=_("Publisher"), null=False, blank=False)
	address = models.CharField(verbose_name=_("Address"), max_length=100, null=False, blank=False)
	year = models.IntegerField(verbose_name=_("Year"), null=False, blank=False)
	reference = models.CharField(verbose_name=_("Reference"), max_length=1000, null=False, blank=False)
	uri = models.URLField(verbose_name=_("URI"), max_length=500, null=False, blank=False)
	
	principal_language = models.CharField(verbose_name=_("Principal Language"), choices=LANGUAGE_CHOICES, max_length=100, null=True, blank=True)
	principal_abstract = models.TextField(verbose_name=_("Principal Abstract"), null=True, blank=True)
	principal_keywords = models.ManyToManyField("KeyWord", verbose_name=_("Principal Keywords"), related_name="principal_keywords", blank=True)

	secondary_language = models.CharField(verbose_name=_("Secondary Language"), choices=LANGUAGE_CHOICES, max_length=100, null=True, blank=True)
	secondary_abstract = models.TextField(verbose_name=_("Secondary Abstract"), null=True, blank=True)
	secondary_keywords = models.ManyToManyField("KeyWord", verbose_name=_("Secondary Keywords"), related_name="secondary_keywords", blank=True)
	
	
	issue_date = models.DateField(verbose_name=_("Issue Date"), null=False, blank=False, auto_now=False)
	file = models.FileField(verbose_name=_(u"File"), upload_to='documents/publication/%Y/%m/%d', null=False, blank=False)
	registration_date = models.DateTimeField(verbose_name=_("Registration Date"), auto_now_add=True, auto_now=False)
	is_final =  models.BooleanField(verbose_name=_(u"Is Final"), default=False,)

	def get_search_fields():
		return (
			("title", _("Title")),
			("principal_abstract", _("Principal Abstract")),
			("secondary_abstract", _("Secondary Abstract")),
			("year", _("Year")),
		)
	def get_output_fields():
		return (
			("title", _("Title")),
			("typology", _("Typology")), 
			("authors", _("Authors")),
		 	("year", _("Year")),
		)

	get_search_fields = staticmethod(get_search_fields)
	get_output_fields = staticmethod(get_output_fields)

	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = orig = slugify(self.title)
			for x in itertools.count(1):
				if not Publication.objects.filter(slug=self.slug).exists():
					break
				self.slug = "%s-%d" % (orig, x)
		super(Publication, self).save(*args, **kwargs)

	def get_typology(self):
		for elem in list(self.TYPOLOGY_CHOICES):
			if elem[0] == self.typology:
				return elem[1]
		return self.typology

	def get_principal_language(self):
		for elem in list(self.LANGUAGE_CHOICES):
			if elem[0] == self.principal_language:
				return elem[1]
		return self.principal_language

	def get_secondary_language(self):
		for elem in list(self.LANGUAGE_CHOICES):
			if elem[0] == self.secondary_language:
				return elem[1]
		return self.secondary_language

	def __unicode__(self):
		return self.title

	def natural_key(self):
		return self.title

	def verbose_name(self):
		return self._meta.verbose_name

	def get_absolute_url(self):
		return reverse_lazy('manager:publication_detail', kwargs={'slug': self.slug})

	class Meta:
		ordering = ['-registration_date']
		verbose_name = _(u"Publication")
		verbose_name_plural = _(u"Publications")

from django.db.models.signals import post_save
from django.dispatch import receiver

def post_save_receiver(sender, instance, created, ** kwargs):
	if not instance.uri:
		instance.uri = reverse_lazy("manager:publication_uri", kwargs={"pk": instance.pk})
		instance.save()

post_save.connect(post_save_receiver, sender=Publication)

manager/views/author_view.py
from django.utils.translation import ugettext_lazy as _
from django.views.generic.list import ListView
from django.http import JsonResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required, permission_required
from django.conf import settings

from base.views import AjaxableResponseMixin, SearchResponseMixin, CSVResponseMixin
from manager.models import Author, Publication

class AuthorListView(SearchResponseMixin, CSVResponseMixin, ListView):
	template_name = 'manager/author/list.html'
	paginate_by = settings.PAGINATE_BY
	model = Author

class AuthorCreateView(AjaxableResponseMixin, CreateView):
	template_name = 'manager/author/form.html'
	model = Author
	fields = ['first_name', 'last_name']
	success_url = reverse_lazy('manager:author_list')

class AuthorUpdateView(UpdateView):
	template_name = 'manager/author/form.html'
	model = Author
	fields = ['first_name', 'last_name']
	success_url = reverse_lazy('manager:author_list')
	
	def form_valid(self, form):
		return super(AuthorUpdateView, self).form_valid(form)

class AuthorDeleteView(DeleteView):
	template_name = 'manager/author/check_delete.html'
	model = Author
	success_url = reverse_lazy('manager:author_list')

class AuthorDetailView(DetailView):
	template_name = 'manager/author/detail.html'
	model = Author

	def get_context_data(self, ** kwargs):
		context = super(AuthorDetailView, self).get_context_data( ** kwargs)
		return context

class AuthorPublicationsView(SearchResponseMixin, SingleObjectMixin, ListView):
	paginate_by = settings.PAGINATE_BY
	template_name = 'manager/author/publications.html'
	model = Publication

	def get(self, request, * args, ** kwargs):
		self.object = self.get_object(queryset=Author.objects.all())
		return super(AuthorPublicationsView, self).get(request, * args, ** kwargs)

	def get_queryset(self):
		queryset = super(AuthorPublicationsView, self).get_queryset()
		return queryset.filter(authors=self.object, is_final=True)

manager/views/collection_view.py
from django.utils.translation import ugettext_lazy as _
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required, permission_required
from django.conf import settings

from base.views import AjaxableResponseMixin, SearchResponseMixin, CSVResponseMixin
from manager.models import Collection, Publication

class CollectionListView(SearchResponseMixin, CSVResponseMixin, ListView):
	template_name = 'manager/collection/list.html'
	paginate_by = settings.PAGINATE_BY
	model = Collection

class CollectionCreateView(AjaxableResponseMixin, CreateView):
	template_name = 'manager/collection/form.html'
	model = Collection
	fields = ['communities','name', 'description']
	success_url = reverse_lazy('manager:collection_list')

	def form_valid(self, form):
		return super(CollectionCreateView, self).form_valid(form)

class CollectionUpdateView(UpdateView):
	template_name = 'manager/collection/form.html'
	model = Collection
	fields = ['communities','name', 'description']
	success_url = reverse_lazy('manager:collection_list')
	
	def form_valid(self, form):
		return super(CollectionUpdateView, self).form_valid(form)

class CollectionDeleteView(DeleteView):
	template_name = 'manager/collection/check_delete.html'
	model = Collection
	success_url = reverse_lazy('manager:collection_list')

class CollectionDetailView(DetailView):
	template_name = 'manager/collection/detail.html'
	model = Collection

	def get_context_data(self, ** kwargs):
		context = super(CollectionDetailView, self).get_context_data( ** kwargs)
		return context

class CollectionPublicationsView(SingleObjectMixin, ListView):
	paginate_by = settings.PAGINATE_BY
	template_name = 'manager/collection/publications.html'
	model = Publication

	def get(self, request, * args, ** kwargs):
		self.object = self.get_object(queryset=Collection.objects.all())
		return super(CollectionPublicationsView, self).get(request, * args, ** kwargs)

	def get_queryset(self):
		queryset = super(CollectionPublicationsView, self).get_queryset()
		return queryset.filter(collection=self.object, is_final=True)

manager/views/community_view.py
from django.utils.translation import ugettext_lazy as _
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required, permission_required
from django.conf import settings

from base.views import AjaxableResponseMixin, SearchResponseMixin, CSVResponseMixin
from manager.models import Community, Collection, Publication

class CommunityListView(SearchResponseMixin, CSVResponseMixin, ListView):
	template_name = 'manager/community/list.html'
	paginate_by = settings.PAGINATE_BY
	model =Community

class CommunityCreateView(AjaxableResponseMixin, CreateView):
	template_name = 'manager/community/form.html'
	model = Community
	fields = ['name',]
	success_url = reverse_lazy('manager:community_list')

class CommunityUpdateView(UpdateView):
	template_name = 'manager/community/form.html'
	model = Community
	fields = ['name',]
	success_url = reverse_lazy('manager:community_list')
	
	def form_valid(self, form):
		return super(CommunityUpdateView, self).form_valid(form)

class CommunityDeleteView(DeleteView):
	template_name = 'manager/community/check_delete.html'
	model = Community
	success_url = reverse_lazy('manager:community_list')

class CommunityDetailView(SingleObjectMixin, ListView):
	paginate_by = settings.PAGINATE_BY
	template_name = 'manager/community/detail.html'
	
	def get(self, request, * args, ** kwargs):
		self.object = self.get_object(queryset=Community.objects.all())
		return super(CommunityDetailView, self).get(request, * args, ** kwargs)
	def get_context_data(self, ** kwargs):
		context = super(CommunityDetailView, self).get_context_data( ** kwargs)
		context['community'] = self.object
		return context
	def get_queryset(self):
		return Collection.objects.filter(communities=self.object.id)

class CommunityPublicationsView(SearchResponseMixin, SingleObjectMixin, ListView):
	paginate_by = settings.PAGINATE_BY
	template_name = 'manager/community/publications.html'
	model = Publication

	def get(self, request, * args, ** kwargs):
		self.object = self.get_object(queryset=Community.objects.all())
		return super(CommunityPublicationsView, self).get(request, * args, ** kwargs)

	def get_queryset(self):
		queryset = super(CommunityPublicationsView, self).get_queryset()
		return queryset.filter(community=self.object, is_final=True)

manager/views/keyword_view.py
from django.utils.translation import ugettext_lazy as _
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required, permission_required
from django.conf import settings
from django.contrib import messages

from base.views import AjaxableResponseMixin, CSVResponseMixin, SearchResponseMixin
from manager.models import Keyword, Publication
from manager.utils.constants import Constants as ConstantsManager

class KeywordListView(SearchResponseMixin, CSVResponseMixin, ListView):
	template_name = 'manager/keyword/list.html'
	paginate_by = settings.PAGINATE_BY
	model = Keyword

class KeywordCreateView(AjaxableResponseMixin, CreateView):
	template_name = 'manager/keyword/form.html'
	model = Keyword
	fields = ['name']
	success_url = reverse_lazy('manager:keyword_list')

class KeywordUpdateView(UpdateView):
	template_name = 'manager/keyword/form.html'
	model = Keyword
	fields = ['name',]
	success_url = reverse_lazy('manager:keyword_list')
	
	def form_valid(self, form):
		messages.success(self.request, ConstantsManager.KEYWORD_SUCCESS_CHANGED)
		return super(KeywordUpdateView, self).form_valid(form)

	def form_invalid(self, form):
		messages.error(self.request, ConstantsManager.KEYWORD_ERROR_CHANGED)
		return super(KeywordUpdateView, self).form_invalid(form)

class KeywordDeleteView(DeleteView):
	template_name = 'manager/keyword/check_delete.html'
	model = Keyword
	success_url = reverse_lazy('manager:keyword_list')

class KeywordDetailView(DetailView):
	template_name = 'manager/keyword/detail.html'
	model = Keyword

	def get_context_data(self, ** kwargs):
		context = super(KeywordDetailView, self).get_context_data( ** kwargs)
		return context

class KeywordPublicationsView(SearchResponseMixin, SingleObjectMixin, ListView):
	paginate_by = settings.PAGINATE_BY
	template_name = 'manager/keyword/publications.html'
	model = Publication

	def get(self, request, * args, ** kwargs):
		self.object = self.get_object(queryset=Keyword.objects.all())
		return super(KeywordPublicationsView, self).get(request, * args, ** kwargs)

	def get_queryset(self):
		queryset = super(KeywordPublicationsView, self).get_queryset()
		principal_keywords = queryset.filter(principal_keywords=self.object, is_final=True)
		secondary_keywords = queryset.filter(secondary_keywords=self.object, is_final=True)
		return list(principal_keywords) + list(secondary_keywords)

manager/templates/manager/publication/_render.html
{% load i18n %}

{% trans "Empty" as Empty %}

<dl class="definition text" itemscope itemtype="http://schema.org/Publication">
	<dt class="col-sm-3">{% trans "Title" %}:</dt>
	<dd class="col-sm-9" itemprop="title">{{ publication.title|default:Empty }}</dd>

	<dt class="col-sm-3">{% trans "Typology" %}:</dt>
	<dd class="col-sm-9" itemprop="typology">{{ publication.get_typology|default:Empty }}</dd>

	<dt class="col-sm-3">{% trans "Authors" %}:</dt>
	<dd class="col-sm-9" itemprop="authors">
		{% for author in publication.authors.all %}
			<a class="tag tag-primary" href="{% url 'manager:author_detail' slug=author.slug %}">
				<i class="fa fa-graduation-cap"></i>
				{{ author.reference_name }}	
			</a>
		{% empty %}
			{{ Empty }}
		{% endfor %}
	</dd>

	<dt class="col-sm-3">{% trans "Subjects" %}</dt>
	<dd class="col-sm-9" itemprop="subjects">
		{% for subject in publication.subjects.all %}
			<a class="tag tag-primary" href="{% url 'manager:subject_detail' slug=subject.slug %}">
				<i class="fa fa-flag"></i>
				{{ subject.name }}		
			</a>
		{% empty %}
			{{ Empty }}	
		{% endfor %}
	</dd>

	<dt class="col-sm-3">{% trans "Community" %}:</dt>
	<dd class="col-sm-9" itemprop="community">
		<a class="tag tag-primary" href="{% url 'manager:community_detail' slug=publication.community.slug %}">
			<i class="fa fa-university"></i>
			{{ publication.community|default:Empty }}		
		</a>
	</dd>

	<dt class="col-sm-3">{% trans "Collection" %}:</dt>
	<dd class="col-sm-9" itemprop="collection">
		<a class="tag tag-primary" href="{% url 'manager:collection_detail' slug=publication.collection.slug %}">
			<i class="fa fa-object-group"></i>
			{{ publication.collection|default:Empty }}		
		</a>
	</dd>

	<dt class="col-sm-3">{% trans "Publisher" %}:</dt>
	<dd class="col-sm-9" itemprop="publisher">
		<a class="tag tag-primary" href="{% url 'manager:publisher_detail' slug=publication.publisher.slug %}">
			<i class="fa fa-newspaper-o"></i>
			{{ publication.publisher|default:Empty }}
		</a>
	</dd>

	<dt class="col-sm-3">{% trans "Address" %}:</dt>
	<dd class="col-sm-9" itemprop="address">{{ publication.address|default:Empty }}</dd>

	<dt class="col-sm-3">{% trans "Year" %}:</dt>
	<dd class="col-sm-9" itemprop="year">{{ publication.year|default:Empty }}</dd>

	<dt class="col-sm-3">{% trans "Reference" %}:</dt>
	<dd class="col-sm-9" itemprop="reference">{{ publication.reference|default:Empty }}</dd>

	<dt class="col-sm-3">{% trans "URI" %}:</dt>
	<dd class="col-sm-9" itemprop="uri">
		<a href="{{ request.get_host }}{{ publication.uri }}">
			{{ request.get_host }}{{ publication.uri }}
		</a>
	</dd>

	<dt class="col-sm-3">{% trans "Principal Language" %}:</dt>
	<dd class="col-sm-9" itemprop="principal_language">{{ publication.get_principal_language|default:Empty }}</dd>

	<dt class="col-sm-3">{% trans "Principal Abstract" %}:</dt>
	<dd class="col-sm-9" itemprop="principal_abstract">
		{{ publication.principal_abstract|default:Empty }}
	</dd>

	<dt class="col-sm-3">{% trans "Principal Keywords" %}:</dt>
	<dd class="col-sm-9" itemprop="principal_keywords">
		{% for keyword in publication.principal_keywords.all %}
		<a class="tag tag-primary" href="{% url 'manager:keyword_detail' slug=keyword.slug %}">
			<i class="fa fa-tags"></i>
			{{ keyword }}
		</a>
		{% empty %}
			{{ Empty }}
		{% endfor %}
	</dd>

	<dt class="col-sm-3">{% trans "Secondary Language" %}:</dt>
	<dd class="col-sm-9" itemprop="secondary_language">
		{{ publication.get_secondary_language|default:Empty }}
	</dd>

	<dt class="col-sm-3">{% trans "Secondary Abstract" %}:</dt>
	<dd class="col-sm-9" itemprop="secondary_abstract">
		{{ publication.secondary_abstract|default:Empty }}
	</dd>

	<dt class="col-sm-3">{% trans "Secondary Keywords" %}:</dt>
	<dd class="col-sm-9" itemprop="secondary_keywords">
		{% for keyword in publication.secondary_keywords.all %}
		<a class="tag tag-primary" href="{% url 'manager:keyword_detail' slug=keyword.slug %}">
			<i class="fa fa-tags"></i>
			{{ keyword }}
		</a>
		{% empty %}
			{{ Empty }}
		{% endfor %}
	</dd>

	<dt class="col-sm-3">{% trans "Issue Date" %}:</dt>
	<dd class="col-sm-9" itemprop="issue_date">{{ publication.issue_date|default:Empty }}</dd>

	<dt class="col-sm-3">{% trans "File" %}:</dt>
	<dd class="col-sm-9" itemprop="file">
		<a href="{{ publication.file.url }}" target="_blank">
			<i class="fa fa-download"></i>
			{% trans "Download" %}
		</a>
	</dd>
</dl>

manager/templates/manager/publication/check_delete.html
{% extends "manager/publication/list.html" %}


{% load i18n static %}

{% block title %}{% endblock %}

{% block stylesheet %}
{% endblock %}

{% block breadcrumbs %}
	{{ block.super }}
	<a href="{% url 'manager:publication_delete' slug=object.slug %}" class="breadcrumb-item" >
		<i class="fa fa-remove"></i>
		{% trans "Confirm delete" %}
	</a>
{% endblock %}

{%  block page_title %}{% trans "Confirm delete" %}{% endblock %}

{% block content %}
	{% include 'base/_check_delete.html' %}
{% endblock %}

manager/templates/manager/publication/detail.html
{% extends "manager/publication/list.html" %}


{% load i18n static %}

{% block title %}{% endblock %}

{% block stylesheet %}
{% endblock %}

{% block breadcrumbs %}
	{{ block.super }}
	<a href="{% url 'manager:publication_detail' slug=publication.slug %}" class="breadcrumb-item" >
		<i class="fa fa fa-book"></i>
		{{ publication.title|truncatewords:"6" }}
	</a>
{% endblock %}

{%  block page_title %}
	{{ publication.title|truncatewords:"6" }}
	<div class="float-xs-right">
		{% if perms.manager.change_publication %}
		<a href="{% url 'manager:publication_update' slug=publication.slug %}" class="btn btn-info" data-toggle="tooltip" title="{% trans "Edit" %}">
			<i class="fa fa-edit"></i>
		</a>
		{% endif %}
		{% if perms.manager.delete_publication %}
		<a href="{% url 'manager:publication_delete' slug=publication.slug %}" class="btn btn-danger" data-toggle="tooltip" title="{% trans "Delete" %}">
			<i class="fa fa-remove"></i>
		</a>
		{% endif %}
	</div>
{% endblock %}

{% block content %}
	{% include 'manager/publication/_render.html' %}
{% endblock %}

manager/templates/manager/publication/form.html
{% extends "manager/publication/list.html" %}


{% load i18n static %}

{% block title %}{% endblock %}

{% block stylesheet %}
{% endblock %}

{% block breadcrumbs %}
	{{ block.super }}
	<a href="{% url 'manager:publication_create' %}" class="breadcrumb-item" >
		{% trans "Form Publication" %}
	</a>
{% endblock %}

{%  block page_title %}{% trans "Form Publication" %}{% endblock %}

{% block content %}	
	{% include "base/_form.html" %}
{% endblock %}

{% block js %}
	{{ block.super }}
	{% include "base/imports/calendar.html" %}
	{% include "base/imports/select2.html" %}
	{% include "base/imports/reverse.html" %}
{% endblock %}

{% block scripts %}
	{{ block.super }}

	<script type="text/javascript">
		var fields = [
			{id:'#id_subjects', url: Urls['manager:subject_create']()},
			{id:'#id_authors', url: Urls['manager:author_create']()},
			{id:'#id_community', url: Urls['manager:community_create']()},
			{id:'#id_collection', url: Urls['manager:collection_create']()},
			{id:'#id_publisher', url: Urls['manager:publisher_create']()},
			{id:'#id_principal_keywords', url: Urls['manager:keyword_create']()},
			{id:'#id_secondary_keywords', url: Urls['manager:keyword_create']()},
		];
		create_objects(fields);
	</script>
{% endblock %}

manager/templates/manager/publication/list.html
{% extends "manager/index.html" %}


{% load i18n static %}

{% block title %}{% endblock %}

{% block stylesheet %}
{% endblock %}

{% block publications %}active{% endblock %}

{% block breadcrumbs %}
	{{ block.super }}
	<a href="{% url 'manager:publication_list' %}" class="breadcrumb-item" >
		<i class="fa fa-book"></i>
		{% trans "Publications" %}
	</a>
{% endblock %}

{%  block page_title %}{% trans "List of Publications" %}{% endblock %}

{% block content %}
	<div class="col-md-4">
	<div class="row">
	{% if perms.manager.add_publication %}
		<a href="{% url 'manager:publication_create' %}" class="btn btn-success">
			<i class="fa fa-plus"></i>
			{% trans "New Publication" %}
		</a>
	{% endif %}
	</div>
	</div>

	<div class="col-md-8">
	<div class="row float-xs-right">
		{% include "base/_form_search.html" %}
	</div>
	</div>

	<table class="table table-bordered table-striped table-hover text">
		<thead class="thead-inverse">
			<tr>
				<th>
					{% trans "Title" %}
				</th>
				<th>
					{% trans "Typology" %}
				</th>
				<th>
					{% trans "Authors" %}
				</th>
			</tr>
		</thead>

		<tbody>
			{% for publication in object_list %}
				<tr>
					<td>
						<a href="{% url 'manager:publication_detail' slug=publication.slug %}">
							{{ publication.title }}	
						</a>
					</td>
					<td>
						{{ publication.get_typology|title }}	
					</td>
					<td>
						{% for author in publication.authors.all %}
							<a href="{% url 'manager:author_detail' slug=author.slug %}" class="tag tag-primary">
								{{ author.reference_name }}
							</a>
						{% endfor %}
					</td>
				</tr>
			{% empty %}
				<tr>
					<td class="text-xs-center">{% trans "No Publication found!" %}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	{% include "base/_paginate.html" %}
{% endblock %}