Repository/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse_lazy
from django.views.i18n import JavaScriptCatalog
from django_js_reverse.views import urls_js
from django.views.decorators.cache import cache_page
from django.utils.translation import ugettext_lazy as _
from django.conf.urls.i18n import i18n_patterns
from django.views.static import serve

import settings

js_info_dict = {
	'app_names': ('Repository.manager',),
}

urlpatterns = i18n_patterns(
	url(r'^$', RedirectView.as_view(url=reverse_lazy('manager:home'), permanent=False), name='home'),
	url(_(r'^manager/'), include('manager.urls', namespace="manager", app_name="manager"), name='manager'),
	url(_(r'^authentication/'), include('authentication.urls', namespace="authentication", app_name="authentication"), name='authentication'),
	url(_(r'^submission/'), include('submission.urls', namespace="submission", app_name="submission"), name='submission'),
	url(_(r'^inbox/'), include('inbox.urls', namespace="inbox", app_name="inbox"), name='inbox'),

	url(_(r'^about$'), TemplateView.as_view(template_name="base/about.html"), name="about"),
	url(_(r'^terms$'), TemplateView.as_view(template_name="base/terms.html"), name="terms"),
	url(_(r'^policies$'), TemplateView.as_view(template_name="base/policies.html"), name="policies"),
	url(_(r'^contact_us$'), TemplateView.as_view(template_name="base/contact_us.html"), name="contact_us"),
		
	url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,}),
	url(r'^i18n/', include('django.conf.urls.i18n')),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^rosetta/', include('rosetta.urls')),
	url(r'^jsreverse/$', cache_page(3600)(urls_js), name='js_reverse'),
	url(r'^jsi18n/$', JavaScriptCatalog.as_view(packages=['base', 'authentication', 'manager', 'submission', 'inbox', ]), name='javascript-catalog'),
)

submission/models/event.py
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse_lazy
from django.db import models
import itertools
import datetime

from manager.models import Community, Collection, Publisher, Subject

class Event(models.Model):
	TYPOLOGY_CHOICES = (
		(u'conference', _(u'Conference')),
		(u'workshop', _(u'Workshop')),
	)
	slug = models.SlugField(verbose_name=_('Slug'), max_length=500, blank=True, unique=True)
	name = models.CharField(verbose_name=_("Name"), max_length=100, null=False, blank=False)
	description = models.TextField(verbose_name=_("description"), null=False, blank=False)
	typology = models.CharField(verbose_name=_("Typology"), choices=TYPOLOGY_CHOICES, max_length=100, null=False, blank=False)
	date = models.DateField(verbose_name=_("Date"), null=False, blank=False)
	address = models.CharField(verbose_name=_("Address"), max_length=100, null=False, blank=False)	
	image = models.FileField(verbose_name=_(u"Image"), upload_to='documents/event/images/%Y/%m/%d')
	
	subjects = models.ManyToManyField(Subject, verbose_name=_("Subjects"), blank=False)
	communities = models.ManyToManyField(Community, verbose_name=_("Communities"), blank=False)
	collections = models.ManyToManyField(Collection, verbose_name=_("Collections"), blank=False)
	publishers = models.ManyToManyField(Publisher, verbose_name=_("Publishers"), blank=False)
	
	submission_1_open = models.DateField(verbose_name=_("Submission 1 Open"), null=False, blank=False)
	submission_1_close = models.DateField(verbose_name=_("Submission 1 Close"), null=False, blank=False)

	review_open = models.DateField(verbose_name=_("Review Open"), null=False, blank=False)
	review_close = models.DateField(verbose_name=_("Review Close"), null=False, blank=False)
	
	submission_2_open = models.DateField(verbose_name=_("Submission 2 Open"), null=False, blank=False)
	submission_2_close = models.DateField(verbose_name=_("Submission 2 Close"), null=False, blank=False)

	registration_date = models.DateTimeField(verbose_name=_("Registration Date"), auto_now_add=True, auto_now=False)

	def get_search_fields():
		return (
			("name", _("Name")),
			("description", _("Description")),
		)
	def get_output_fields():
		return (
			("name", _("Name")),
			("typology", _("Typology")),
			("address", _("Address")),
			("community", _("Community")),
			("publisher", _("Publisher")),
			("date", _("Date")),
			("submission_1_open", _("Submission 1 Open")),
			("review_open", _("Review Open")),
			("submission_2_open", _("Submission 2 Open")),
				
		)

	get_search_fields = staticmethod(get_search_fields)
	get_output_fields = staticmethod(get_output_fields)

	def stage(self):
		now = datetime.date.today()
		if now < self.submission_1_open:
			return {'type': 'before_period', 'text': _('Before the period')}
		elif self.submission_1_open <= now <= self.submission_1_close:
			return {'type': 'submission_open_1', 'text': _('Submission Open 1')}
		elif self.submission_1_close < now < self.submission_2_open:
			return {'type': 'reviewing', 'text': _('Reviewing...')}
		elif self.submission_2_open <= now <= self.submission_2_close:
			return {'type': 'submission_open_2', 'text': _('Submission Open 2')}
		elif now > self.submission_2_close:
			return {'type': 'submission_complete', 'text': _('Submission Complete')}
		else:
			return {'type': 'out_of_period', 'text': _('Out of period')}

	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = orig = slugify(self.name)
			for x in itertools.count(1):
				if not Event.objects.filter(slug=self.slug).exists():
					break
				self.slug = "%s-%d" % (orig, x)
		super(Event, self).save(*args, **kwargs)

	def __unicode__(self):
		return self.name

	def natural_key(self):
		return self.name

	def verbose_name(self):
		return self._meta.verbose_name

	def get_absolute_url(self):
		return reverse_lazy('submission:event_detail', kwargs={'slug': self.slug})

	class Meta:
		ordering = ['-date']
		verbose_name = _(u'Event')
		verbose_name_plural = _(u'Event')

submission/forms/submission_form.py
# -*- encoding=utf-8 -*-

from django.forms import ModelForm
from submission.models import Submission


class SubmissionForm(ModelForm):
	def __init__(self, event, *args, **kwargs):
		super(SubmissionForm, self).__init__(*args, **kwargs)
		self.fields['subjects'].queryset = event.subjects.all()
		self.fields['community'].queryset = event.communities.all()
		self.fields['collection'].queryset = event.collections.all()
		self.fields['publisher'].queryset = event.publishers.all()

	class Meta:
		model = Submission
		fields = ('title', 'typology', 'authors', 'subjects', 'community', 'collection', 'publisher', 'reference','principal_language', 'principal_abstract', 'principal_keywords', 'secondary_language', 'secondary_abstract', 'secondary_keywords', 'file')

submission/views/event_view.py
from django.utils.translation import ugettext_lazy as _
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required, permission_required
from django.conf import settings

from submission.models import Event

from base.views import  SearchResponseMixin, CSVResponseMixin

class EventListView(SearchResponseMixin, CSVResponseMixin, ListView):
	template_name = 'submission/event/list.html'
	paginate_by = settings.PAGINATE_BY
	model = Event

class EventCreateView(CreateView):
	template_name = 'submission/event/form.html'
	model = Event
	fields = ['name', 'description', 'typology', 'typology', 'date', 'address', 'image', 
			 'subjects', 'communities', 'collections', 'publishers', 
			 'submission_1_open', 'submission_1_close', 'review_open', 'review_close', 'submission_2_open', 'submission_2_close']

	def get_success_url(self):
		return reverse_lazy('submission:event_detail', kwargs={'slug':self.object.slug})

	def form_valid(self, form):
		return super(EventCreateView, self).form_valid(form)

class EventUpdateView(UpdateView):
	template_name = 'submission/event/form.html'
	model = Event
	fields = ['name', 'description', 'typology', 'typology', 'date', 'address', 'image', 
			 'subjects', 'communities', 'collections', 'publishers', 
			 'submission_1_open', 'submission_1_close', 'review_open', 'review_close', 'submission_2_open', 'submission_2_close']
	
	def get_success_url(self):
		return reverse_lazy('submission:event_detail', kwargs={'slug':self.object.slug})

class EventDeleteView(DeleteView):
	template_name = 'submission/event/check_delete.html'
	model = Event
	success_url = reverse_lazy('submission:event_list')

class EventDetailView(DetailView):
	template_name = 'submission/event/detail.html'
	model = Event

submission/views/report_view.py
from django.utils.translation import ugettext_lazy as _
from django.views.generic import View
from django.http import JsonResponse

from manager.models import Publication
from submission.models import Event, Submission

from base.utils import Export

class ReportSubmissionView(View):
	def get(self, request, * args, ** kwargs):
		export = Export()
		event = Event.objects.filter(slug=self.kwargs['event_slug']).first()
		submissions = Submission.objects.filter(event=event)
		publications = []
		
		for submission in submissions:
			if self.request.POST['type_report'] == 'all':
				pass
			elif self.request.POST['type_report'] == 'with_review' and not submission.review:
				continue
			elif self.request.POST['type_report'] == 'without_review' and submission.review:
				continue
			elif self.request.POST['type_report'] == 'is_final' and not submission.publication.is_final:
				continue
			elif self.request.POST['type_report'] == 'is_not_final' and submission.publication.is_final:
				continue
			publications.append(submission.publication)

		return export.to_csv(request, publications, ('title', 'authors','typology'))

submission/views/review_view.py
from django.utils.translation import ugettext_lazy as _
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required, permission_required
from django.conf import settings
from datetime import datetime
from django.http import HttpResponseRedirect

from authentication.models import User
from submission.models import Review, Submission, Event

class ReviewCreateView(CreateView):
	template_name = 'submission/review/form.html'
	model = Review
	fields = ['originality', 'originality_observation', 'technical_merit', 'technical_merit_observation', 
	'clarity', 'clarity_observation','text_quality', 'text_quality_observation', 'relevance', 
	'relevance_observation', 'knowledge_level_revisor', 'knowledge_level_revisor_observation', 'general', 'general_observation',]

	def get_success_url(self):
		event = Event.objects.filter(slug=self.kwargs['event_slug']).first()
		submission = Submission.objects.filter(slug=self.kwargs['submission_slug']).first()
		return reverse_lazy('submission:review_detail_to_review', kwargs={'event_slug':event.slug, 'submission_slug':submission.slug, 'pk': self.object.pk,})

	def get(self, request, * args, ** kwargs):
		event = Event.objects.filter(slug=self.kwargs['event_slug']).first()
		submission = Submission.objects.filter(slug=self.kwargs['submission_slug']).first()
		if not request.user == submission.reviser:
			return HttpResponseRedirect(reverse_lazy('submission:submission_list', kwargs={'event_slug':event.slug}))
		return super(ReviewCreateView, self).get(request)	

	def get_context_data(self, ** kwargs):
		event = Event.objects.filter(slug=self.kwargs['event_slug']).first()
		submission = Submission.objects.filter(slug=self.kwargs['submission_slug']).first()

		context = super(ReviewCreateView, self).get_context_data( ** kwargs)
		context["event"] = event
		context["submission"] = submission
		context["publication"] = submission.publication
		context["review"] = self.object
		return context

	def form_valid(self, form):
		event = Event.objects.filter(slug=self.kwargs['event_slug']).first()
		submission = Submission.objects.filter(slug=self.kwargs['submission_slug']).first()

		review = form.save()
		submission.review = review
		submission.save()
		return super(ReviewCreateView, self).form_valid(form)

class ReviewUpdateView(UpdateView):
	template_name = 'submission/review/form.html'
	model = Review
	fields = ['originality', 'originality_observation', 'technical_merit', 'technical_merit_observation', 
	'clarity', 'clarity_observation','text_quality', 'text_quality_observation', 'relevance', 
	'relevance_observation', 'knowledge_level_revisor', 'knowledge_level_revisor_observation', 'general', 'general_observation',]

	def get_success_url(self):
		event = Event.objects.filter(slug=self.kwargs['event_slug']).first()
		submission = Submission.objects.filter(slug=self.kwargs['submission_slug']).first()
		return reverse_lazy('submission:review_detail_to_review', kwargs={'event_slug':event.slug, 'submission_slug':submission.slug, 'pk': self.object.pk,})

	def get(self, request, * args, ** kwargs):
		event = Event.objects.filter(slug=self.kwargs['event_slug']).first()
		submission = Submission.objects.filter(slug=self.kwargs['submission_slug']).first()
		if not request.user == submission.reviser:
			return HttpResponseRedirect(reverse_lazy('submission:submission_list', kwargs={'event_slug':event.slug}))
		return super(ReviewUpdateView, self).get(request)

	def get_context_data(self, ** kwargs):
		event = Event.objects.filter(slug=self.kwargs['event_slug']).first()
		submission = Submission.objects.filter(slug=self.kwargs['submission_slug']).first()

		context = super(ReviewUpdateView, self).get_context_data( ** kwargs)
		context["event"] = event
		context["submission"] = submission
		context["publication"] = submission.publication
		context["review"] = self.object
		return context

class ReviewDeleteView(DeleteView):
	template_name = 'submission/review/check_delete.html'
	model = Review

	def get_success_url(self):
		event = Event.objects.filter(slug=self.kwargs['event_slug']).first()
		submission = Submission.objects.filter(slug=self.kwargs['submission_slug']).first()
		return reverse_lazy('submission:submission_detail_to_review', kwargs={'event_slug':event.slug, 'slug':submission.slug,})

	def get_context_data(self, ** kwargs):
		event = Event.objects.filter(slug=self.kwargs['event_slug']).first()
		submission = Submission.objects.filter(slug=self.kwargs['submission_slug']).first()

		context = super(ReviewDeleteView, self).get_context_data( ** kwargs)
		context["event"] = event
		context["submission"] = submission
		context["publication"] = submission.publication
		context["review"] = self.object
		return context

	def get(self, request, * args, ** kwargs):
		event = Event.objects.filter(slug=self.kwargs['event_slug']).first()
		submission = Submission.objects.filter(slug=self.kwargs['submission_slug']).first()
		if not request.user == submission.reviser:
			return HttpResponseRedirect(reverse_lazy('submission:submission_list', kwargs={'event_slug':event.slug}))
		return super(ReviewDeleteView, self).get(request)
	def post(self, request, * args, ** kwargs):
		event = Event.objects.filter(slug=self.kwargs['event_slug']).first()
		submission = Submission.objects.filter(slug=self.kwargs['submission_slug']).first()
		submission.review = None
		submission.save()
		return super(ReviewDeleteView, self).post(request)

class ReviewDetailView(DetailView):
	model = Review

	def get_context_data(self, ** kwargs):
		event = Event.objects.filter(slug=self.kwargs['event_slug']).first()
		submission = Submission.objects.filter(slug=self.kwargs['submission_slug']).first()
		context = super(ReviewDetailView, self).get_context_data( ** kwargs)
		context['event'] = event
		context['publication'] = submission.publication
		context['submission'] = submission
		context['review'] = self.object
		return context

	def get(self, request, * args, ** kwargs):
		event = Event.objects.filter(slug=self.kwargs['event_slug']).first()
		submission = Submission.objects.filter(slug=self.kwargs['submission_slug']).first()

		if request.user == submission.user or request.user == submission.reviser or request.user.is_staff:
			return super(ReviewDetailView, self).get(request)
		else:
			return HttpResponseRedirect(reverse_lazy('submission:submission_list', kwargs={'event_slug':event.slug}))

submission/templates/submission/event/_render.html
{% load i18n %}

{% trans "Empty" as Empty %}

<div class="col-md-6">
	<dl class="definition text" itemscope itemtype="http://schema.org/Event">
	{% comment %}
		<dt class="col-sm-3">{% trans "Subjects" %}:</dt>
		<dd class="col-sm-9" itemprop="subject">
			{% for subject in event.subjects.all %}
				<a href="{% url 'manager:subject_detail' slug=subject.slug %}" class="tag tag-primary" target="_blank">
					<i class="fa fa-flag"></i>
					{{ subject }}		
				</a>
			{% empty %}
				{{ Empty }}	
			{% endfor %}
		</dd>
	{% endcomment %}
		<dt class="col-sm-3">{% trans "Communities" %}:</dt>
		<dd class="col-sm-9" itemprop="community">
			{% for community in event.communities.all %}
				<a href="{% url 'manager:community_detail' slug=community.slug %}" class="tag tag-primary" target="_blank">
					<i class="fa fa-university"></i>
					{{ community }}
				</a>
			{% empty %}
				{{ Empty }}
			{% endfor %}

		</dd>

		<dt class="col-sm-3">{% trans "Collections" %}:</dt>
		<dd class="col-sm-9" itemprop="collection">
			{% for collection in event.collections.all %}
				<a href="{% url 'manager:collection_detail' slug=collection.slug %}" class="tag tag-primary" target="_blank">
					<i class="fa fa-object-group"></i>
					{{ collection }}		
				</a>
			{% empty %}
				{{ Empty }}
			{% endfor %}
		</dd>

		<dt class="col-sm-3">{% trans "Publishers" %}:</dt>
		<dd class="col-sm-9" itemprop="publishers">
			{% for publisher in event.publishers.all %}
				<a href="{% url 'manager:publisher_detail' slug=publisher.slug %}" class="tag tag-primary" target="_blank">
					<i class="fa fa fa-newspaper-o"></i>
					{{ publisher }}
				</a>
			{% empty %}
				{{ Empty }}
			{% endfor %}
		</dd>

		<dt class="col-sm-3">{% trans "Date" %}:</dt>
		<dd class="col-sm-9" itemprop="date">{{ event.date }}</dd>

		<dt class="col-sm-3">{% trans "Address" %}:</dt>
		<dd class="col-sm-9" itemprop="address">{{ event.address }}</dd>
	</dl>
</div>
<div class="col-md-6">
	<dl class="definition text" itemscope itemtype="http://schema.org/Date">
		<dt class="col-sm-5">{% trans "Submission 1" %}:</dt>
		<dd class="col-sm-7" itemprop="submission_1">
			{{ event.submission_1_open }} -- {{ event.submission_1_close }}
		</dd>

		<dt class="col-sm-5">{% trans "Review" %}:</dt>
		<dd class="col-sm-7" itemprop="review">
			{{ event.review_open }} -- {{ event.review_close }}
		</dd>

		<dt class="col-sm-5">{% trans "Submission 2" %}:</dt>
		<dd class="col-sm-7" itemprop="submission_2">
			{{ event.submission_2_open }} -- {{ event.submission_2_close }}
		</dd>
	</dl>
	{% include "submission/event/_render_buttons_actions.html" %}
</div>

submission/templates/submission/event/_render_buttons_actions.html
{% load i18n static %}

<div class="btn-group btn-group-md" role="group" aria-label="Large button group">
	{% if event.stage.type == 'before_period' %}
		{% blocktrans with date=event.submission_1_open %}
			Submissions in {{ date }}
		{% endblocktrans %}
	{% else %}
		<a href="{% url 'submission:submission_list' event_slug=event.slug %}" data-toggle="tooltip" class="btn btn-secondary" title="{% trans "List my submissions" %}">
			<i class="fa fa-upload"></i>
			{% trans "My Submissions" %}
		</a>
	{% endif %}

	{% if perms.submission.list_submission_to_review and event.stage.type != 'before_period' and event.stage.type != 'out_of_period'  %}
		<a href="{% url 'submission:submission_list_to_review' event_slug=event.slug %}" data-toggle="tooltip" class="btn btn-secondary" title="{% trans "Submission to review" %}">
			<i class="fa fa-file-text-o"></i>
			{% trans "To Review" %}
		</a>
	{% endif %}

	{% if event.stage.type == 'submission_complete' %}
		<a href="{% url 'submission:submission_final' event_slug=event.slug %}" data-toggle="tooltip" class="btn btn-secondary" title="{% trans "All publications of event" %}">
			<i class="fa fa-book"></i>
			{% trans "All Publications" %}
		</a>
	{% endif %}
</div>

submission/templates/submission/event/check_delete.html
{% extends "submission/event/list.html" %}


{% load i18n static %}

{% block title %}{% endblock %}

{% block stylesheet %}
{% endblock %}

{% block breadcrumbs %}
	{{ block.super }}
	<a href="{% url 'submission:event_delete' slug=object.slug %}" class="breadcrumb-item" >
		<i class="fa fa-remove"></i>
		{% trans "Confirm delete" %}
	</a>
{% endblock %}

{%  block page_title %}{% trans "Confirm delete" %}{% endblock %}

{% block content %}
	{% include 'base/_check_delete.html' %}
{% endblock %}

submission/templates/submission/event/detail.html
{% extends "submission/event/list.html" %}


{% load i18n %}

{% block title %}{% endblock %}

{% block stylesheet %}
{% endblock %}

{% block breadcrumbs %}
	{{ block.super }}
	<a href="{% url 'submission:event_detail' slug=event.slug %}" class="breadcrumb-item" >
		<i class="fa fa-hashtag"></i>
		{{ event.name }}
	</a>
{% endblock %}

{%  block page_title %}
	{{ event.name }}
	<div class="float-xs-right">
		{% if perms.submission.change_event %}
		<a href="{% url 'submission:event_update' slug=event.slug %}" class="btn btn-info" data-toggle="tooltip" title="{% trans "Edit" %}">
			<i class="fa fa-edit"></i>
		</a>
		{% endif %}
		{% if perms.submission.delete_event %}
		<a href="{% url 'submission:event_delete' slug=event.slug %}" class="btn btn-danger" data-toggle="tooltip" title="{% trans "Delete" %}">
			<i class="fa fa-remove"></i>
		</a>
		{% endif %}
	</div>
{% endblock %}

{% block content %}
<div class="text">
	<div class="col-md-12">
		<div class="row">	
			<p class="lead text-justify">
				<img src="{{ event.image.url }}" width="300px" height="200px" style="float: left; margin: 0px 10px 10px 0px ;" />
				{{ event.description }}
			</p>
		</div>
	</div>
	<hr class="divider"/>
	{% include 'submission/event/_render.html' %}
</div>
{% endblock %}

submission/templates/submission/event/form.html
{% extends "submission/event/list.html" %}


{% load i18n static %}

{% block title %}{% endblock %}

{% block stylesheet %}
{% endblock %}

{% block breadcrumbs %}
	{{ block.super }}
	<a href="{% url 'submission:event_create' %}" class="breadcrumb-item" >
		{% trans "Form Event" %}
	</a>
{% endblock %}

{% block page_title %}{% trans "Form Event" %}{% endblock %}

{% block content %}		
	{% include "base/_form.html" %}
{% endblock %}

{% block js %}
	{{ block.super }}
	{% include "base/imports/mask.html" %}
	{% include "base/imports/select2.html" %}
	{% include "base/imports/reverse.html" %}
{% endblock %}

{% block scripts %}
	{{ block.super }}

	<script type="text/javascript">
		var fields = [
			{id:'#id_subjects', url: Urls['manager:subject_create']()},
			{id:'#id_communities', url: Urls['manager:community_create']()},
			{id:'#id_collections', url: Urls['manager:collection_create']()},
			{id:'#id_publishers', url: Urls['manager:publisher_create']()},
		];
		create_objects(fields);
	</script>
{% endblock %}

submission/templates/submission/event/list.html
{% extends "submission/index.html" %}


{% load i18n %}

{% block title %}{% endblock %}

{% block stylesheet %}
{% endblock %}

{% block events %}active{% endblock %}

{%  block page_title %}{% trans "List of Events" %}{% endblock %}

{% block breadcrumbs %}
	{{ block.super }}
	<a href="{% url 'submission:event_list' %}" class="breadcrumb-item" >
		<i class="fa fa-hashtag"></i>
		{% trans "Events" %}
	</a>
{% endblock %}

{% block content %}
	<div class="col-md-4">
	<div class="row">
	{% if perms.submission.add_event %}
		<a href="{% url 'submission:event_create'  %}" class="btn btn-success">
			<i class="fa fa-plus"></i>
			{% trans "New Event" %}
		</a>
	{% endif %}
	</div>
	</div>

	<div class="col-md-8">
	<div class="row float-xs-right">
		{% include "base/_form_search.html" %}
	</div>
	</div>

		{% for event in object_list %}

		<div class="col-xs-12 col-sm-12 col-md-12">
			<div class="card card-block row">
				<div class="col-md-4">
					<a href="{{ event.image.url }}" class="boxer" title="{{ event.name }}" data-gallery="gallery">
						<img class="card-img-top" src="{{ event.image.url }}" width="100%" height="200px">
					</a>
				</div>
				<div class="col-md-8">
					<h3 class="card-title">
						<a href="{% url 'submission:event_detail' slug=event.slug  %}" class="btn-link">
						{{ event.name }}
						</a>
					</h3>
					<p class="card-text text-justify">
						{{ event.description|truncatewords:30 }}
						<a href="{% url 'submission:event_detail' slug=event.slug  %}">{% trans "plus" %}</a>
					</p>
					<p class="card-text">
						<div class="col-md-4">
							{% trans "Date" %}: {{ event.date }}
						</div>
						<div class="col-md-4">
							{% trans "Stage" %}: 
							{% if event.stage.type == 'before_period' %}
							<label class="tag tag-info">
							{% elif event.stage.type == 'submission_open_1' or event.stage.type == 'submission_open_2'  %}
							<label class="tag tag-success">
							{% elif event.stage.type == 'submission_close'  %}
							<label class="tag tag-danger">
							{% else %}
							<label class="tag tag-primary">
							{% endif %}
								{{ event.stage.text }}
							</label>
						</div>
						<div class="col-md-4">
							
						</div>
					</p>
					{% include "submission/event/_render_buttons_actions.html" %}
				</div>
			</div>
		</div>
		{% endfor %}

		{% include "base/_paginate.html" %}

{% endblock %}

{% block js %}
	{{ block.super }}
	{% include "base/imports/boxer.html" %}
{% endblock %}