Repository/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse_lazy
from django.views.i18n import JavaScriptCatalog
from django_js_reverse.views import urls_js
from django.views.decorators.cache import cache_page
from django.utils.translation import ugettext_lazy as _
from django.conf.urls.i18n import i18n_patterns
from django.views.static import serve

import settings

js_info_dict = {
	'app_names': ('Repository.manager',),
}

urlpatterns = i18n_patterns(
	url(r'^$', RedirectView.as_view(url=reverse_lazy('manager:home'), permanent=False), name='home'),
	url(_(r'^manager/'), include('manager.urls', namespace="manager", app_name="manager"), name='manager'),
	url(_(r'^authentication/'), include('authentication.urls', namespace="authentication", app_name="authentication"), name='authentication'),
	url(_(r'^submission/'), include('submission.urls', namespace="submission", app_name="submission"), name='submission'),
	url(_(r'^inbox/'), include('inbox.urls', namespace="inbox", app_name="inbox"), name='inbox'),

	url(_(r'^about$'), TemplateView.as_view(template_name="base/about.html"), name="about"),
	url(_(r'^terms$'), TemplateView.as_view(template_name="base/terms.html"), name="terms"),
	url(_(r'^policies$'), TemplateView.as_view(template_name="base/policies.html"), name="policies"),
	url(_(r'^contact_us$'), TemplateView.as_view(template_name="base/contact_us.html"), name="contact_us"),
		
	url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,}),
	url(r'^i18n/', include('django.conf.urls.i18n')),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^rosetta/', include('rosetta.urls')),
	url(r'^jsreverse/$', cache_page(3600)(urls_js), name='js_reverse'),
	url(r'^jsi18n/$', JavaScriptCatalog.as_view(packages=['base', 'authentication', 'manager', 'submission', 'inbox', ]), name='javascript-catalog'),
)

manager/models/author.py
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse_lazy
from django.db import models
import itertools


class Author(models.Model):
	
	first_name = models.CharField(verbose_name=_("First name"), max_length=100, null=False, blank=False)
	last_name = models.CharField(verbose_name=_("Last name"), max_length=100, null=False, blank=False)
	reference_name = models.CharField(verbose_name=_("Reference name"), max_length=200, null=True, blank=True)
	slug = models.SlugField(verbose_name=_('slug'), max_length=60, blank=True, unique=True)

	registration_date = models.DateTimeField(verbose_name=_("Registration Date"), auto_now_add=True, auto_now=False)
	
	def get_search_fields():
		return (
			("first_name", _("First Name")), 
			("last_name", _("Last Name")),
		)
	def get_output_fields():
		return (
			("first_name", _("First Name")), 
			("last_name", _("Last Name")),
			("reference_name", _("Reference name")),
		)

	get_search_fields = staticmethod(get_search_fields)
	get_output_fields = staticmethod(get_output_fields)

	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = orig = slugify("%s-%s" % (self.first_name, self.last_name) )
			for x in itertools.count(1):
				if not Author.objects.filter(slug=self.slug).exists():
					break
				self.slug = "%s-%d" % (orig, x)
		self.reference_name = self.last_name.upper() + ", " + self.first_name
		super(Author, self).save(*args, **kwargs)

	def __unicode__(self):
		return self.reference_name

	def natural_key(self):
		return self.reference_name

	def verbose_name(self):
		return self._meta.verbose_name

	def get_absolute_url(self):
		return reverse_lazy('manager:author_detail', kwargs={'slug': self.slug})

	class Meta:
		ordering = ['-registration_date']
		verbose_name = _(u"Author")
		verbose_name_plural = _(u"Authors")

manager/models/community.py
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse_lazy
from django.db import models
import itertools

class Community(models.Model):
	name = models.CharField(verbose_name=_("Name"), max_length=100, unique=True, null=False, blank=False)
	slug = models.SlugField(_('slug'), max_length=60, blank=True, unique=True)
	
	registration_date = models.DateTimeField(verbose_name=_("Registration Date"), auto_now_add=True, auto_now=False)

	def get_search_fields():
		return (
			("name", _("Name")), 
		)
	def get_output_fields():
		return (
			("name", _("Name")),
		)

	get_search_fields = staticmethod(get_search_fields)
	get_output_fields = staticmethod(get_output_fields)

	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = orig = slugify(self.name)
			for x in itertools.count(1):
				if not Community.objects.filter(slug=self.slug).exists():
					break
				self.slug = "%s-%d" % (orig, x)
		super(Community, self).save(*args, **kwargs)

	def __unicode__(self):
		return self.name

	def natural_key(self):
		return self.name

	def verbose_name(self):
		return self._meta.verbose_name

	def get_absolute_url(self):
		return reverse_lazy('manager:community_detail', kwargs={'slug': self.slug})
	
	class Meta:
		ordering = ['-registration_date']
		verbose_name = _(u"Community")
		verbose_name_plural = _(u"Communities")

manager/views/author_view.py
from django.utils.translation import ugettext_lazy as _
from django.views.generic.list import ListView
from django.http import JsonResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required, permission_required
from django.conf import settings

from base.views import AjaxableResponseMixin, SearchResponseMixin, CSVResponseMixin
from manager.models import Author, Publication

class AuthorListView(SearchResponseMixin, CSVResponseMixin, ListView):
	template_name = 'manager/author/list.html'
	paginate_by = settings.PAGINATE_BY
	model = Author

class AuthorCreateView(AjaxableResponseMixin, CreateView):
	template_name = 'manager/author/form.html'
	model = Author
	fields = ['first_name', 'last_name']
	success_url = reverse_lazy('manager:author_list')

class AuthorUpdateView(UpdateView):
	template_name = 'manager/author/form.html'
	model = Author
	fields = ['first_name', 'last_name']
	success_url = reverse_lazy('manager:author_list')
	
	def form_valid(self, form):
		return super(AuthorUpdateView, self).form_valid(form)

class AuthorDeleteView(DeleteView):
	template_name = 'manager/author/check_delete.html'
	model = Author
	success_url = reverse_lazy('manager:author_list')

class AuthorDetailView(DetailView):
	template_name = 'manager/author/detail.html'
	model = Author

	def get_context_data(self, ** kwargs):
		context = super(AuthorDetailView, self).get_context_data( ** kwargs)
		return context

class AuthorPublicationsView(SearchResponseMixin, SingleObjectMixin, ListView):
	paginate_by = settings.PAGINATE_BY
	template_name = 'manager/author/publications.html'
	model = Publication

	def get(self, request, * args, ** kwargs):
		self.object = self.get_object(queryset=Author.objects.all())
		return super(AuthorPublicationsView, self).get(request, * args, ** kwargs)

	def get_queryset(self):
		queryset = super(AuthorPublicationsView, self).get_queryset()
		return queryset.filter(authors=self.object, is_final=True)

manager/views/collection_view.py
from django.utils.translation import ugettext_lazy as _
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required, permission_required
from django.conf import settings

from base.views import AjaxableResponseMixin, SearchResponseMixin, CSVResponseMixin
from manager.models import Collection, Publication

class CollectionListView(SearchResponseMixin, CSVResponseMixin, ListView):
	template_name = 'manager/collection/list.html'
	paginate_by = settings.PAGINATE_BY
	model = Collection

class CollectionCreateView(AjaxableResponseMixin, CreateView):
	template_name = 'manager/collection/form.html'
	model = Collection
	fields = ['communities','name', 'description']
	success_url = reverse_lazy('manager:collection_list')

	def form_valid(self, form):
		return super(CollectionCreateView, self).form_valid(form)

class CollectionUpdateView(UpdateView):
	template_name = 'manager/collection/form.html'
	model = Collection
	fields = ['communities','name', 'description']
	success_url = reverse_lazy('manager:collection_list')
	
	def form_valid(self, form):
		return super(CollectionUpdateView, self).form_valid(form)

class CollectionDeleteView(DeleteView):
	template_name = 'manager/collection/check_delete.html'
	model = Collection
	success_url = reverse_lazy('manager:collection_list')

class CollectionDetailView(DetailView):
	template_name = 'manager/collection/detail.html'
	model = Collection

	def get_context_data(self, ** kwargs):
		context = super(CollectionDetailView, self).get_context_data( ** kwargs)
		return context

class CollectionPublicationsView(SingleObjectMixin, ListView):
	paginate_by = settings.PAGINATE_BY
	template_name = 'manager/collection/publications.html'
	model = Publication

	def get(self, request, * args, ** kwargs):
		self.object = self.get_object(queryset=Collection.objects.all())
		return super(CollectionPublicationsView, self).get(request, * args, ** kwargs)

	def get_queryset(self):
		queryset = super(CollectionPublicationsView, self).get_queryset()
		return queryset.filter(collection=self.object, is_final=True)

manager/views/community_view.py
from django.utils.translation import ugettext_lazy as _
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required, permission_required
from django.conf import settings

from base.views import AjaxableResponseMixin, SearchResponseMixin, CSVResponseMixin
from manager.models import Community, Collection, Publication

class CommunityListView(SearchResponseMixin, CSVResponseMixin, ListView):
	template_name = 'manager/community/list.html'
	paginate_by = settings.PAGINATE_BY
	model =Community

class CommunityCreateView(AjaxableResponseMixin, CreateView):
	template_name = 'manager/community/form.html'
	model = Community
	fields = ['name',]
	success_url = reverse_lazy('manager:community_list')

class CommunityUpdateView(UpdateView):
	template_name = 'manager/community/form.html'
	model = Community
	fields = ['name',]
	success_url = reverse_lazy('manager:community_list')
	
	def form_valid(self, form):
		return super(CommunityUpdateView, self).form_valid(form)

class CommunityDeleteView(DeleteView):
	template_name = 'manager/community/check_delete.html'
	model = Community
	success_url = reverse_lazy('manager:community_list')

class CommunityDetailView(SingleObjectMixin, ListView):
	paginate_by = settings.PAGINATE_BY
	template_name = 'manager/community/detail.html'
	
	def get(self, request, * args, ** kwargs):
		self.object = self.get_object(queryset=Community.objects.all())
		return super(CommunityDetailView, self).get(request, * args, ** kwargs)
	def get_context_data(self, ** kwargs):
		context = super(CommunityDetailView, self).get_context_data( ** kwargs)
		context['community'] = self.object
		return context
	def get_queryset(self):
		return Collection.objects.filter(communities=self.object.id)

class CommunityPublicationsView(SearchResponseMixin, SingleObjectMixin, ListView):
	paginate_by = settings.PAGINATE_BY
	template_name = 'manager/community/publications.html'
	model = Publication

	def get(self, request, * args, ** kwargs):
		self.object = self.get_object(queryset=Community.objects.all())
		return super(CommunityPublicationsView, self).get(request, * args, ** kwargs)

	def get_queryset(self):
		queryset = super(CommunityPublicationsView, self).get_queryset()
		return queryset.filter(community=self.object, is_final=True)

manager/views/keyword_view.py
from django.utils.translation import ugettext_lazy as _
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required, permission_required
from django.conf import settings
from django.contrib import messages

from base.views import AjaxableResponseMixin, CSVResponseMixin, SearchResponseMixin
from manager.models import Keyword, Publication
from manager.utils.constants import Constants as ConstantsManager

class KeywordListView(SearchResponseMixin, CSVResponseMixin, ListView):
	template_name = 'manager/keyword/list.html'
	paginate_by = settings.PAGINATE_BY
	model = Keyword

class KeywordCreateView(AjaxableResponseMixin, CreateView):
	template_name = 'manager/keyword/form.html'
	model = Keyword
	fields = ['name']
	success_url = reverse_lazy('manager:keyword_list')

class KeywordUpdateView(UpdateView):
	template_name = 'manager/keyword/form.html'
	model = Keyword
	fields = ['name',]
	success_url = reverse_lazy('manager:keyword_list')
	
	def form_valid(self, form):
		messages.success(self.request, ConstantsManager.KEYWORD_SUCCESS_CHANGED)
		return super(KeywordUpdateView, self).form_valid(form)

	def form_invalid(self, form):
		messages.error(self.request, ConstantsManager.KEYWORD_ERROR_CHANGED)
		return super(KeywordUpdateView, self).form_invalid(form)

class KeywordDeleteView(DeleteView):
	template_name = 'manager/keyword/check_delete.html'
	model = Keyword
	success_url = reverse_lazy('manager:keyword_list')

class KeywordDetailView(DetailView):
	template_name = 'manager/keyword/detail.html'
	model = Keyword

	def get_context_data(self, ** kwargs):
		context = super(KeywordDetailView, self).get_context_data( ** kwargs)
		return context

class KeywordPublicationsView(SearchResponseMixin, SingleObjectMixin, ListView):
	paginate_by = settings.PAGINATE_BY
	template_name = 'manager/keyword/publications.html'
	model = Publication

	def get(self, request, * args, ** kwargs):
		self.object = self.get_object(queryset=Keyword.objects.all())
		return super(KeywordPublicationsView, self).get(request, * args, ** kwargs)

	def get_queryset(self):
		queryset = super(KeywordPublicationsView, self).get_queryset()
		principal_keywords = queryset.filter(principal_keywords=self.object, is_final=True)
		secondary_keywords = queryset.filter(secondary_keywords=self.object, is_final=True)
		return list(principal_keywords) + list(secondary_keywords)

manager/views/publication_view.py
from django.utils.translation import ugettext_lazy as _
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required, permission_required
from django.conf import settings
import hashlib

from base.views import AjaxableResponseMixin, SearchResponseMixin, CSVResponseMixin
from manager.models import Publication

class PublicationListView(SearchResponseMixin, CSVResponseMixin, ListView):
	template_name = 'manager/publication/list.html'
	paginate_by = settings.PAGINATE_BY
	model = Publication

	def get_queryset(self):
		queryset = super(PublicationListView, self).get_queryset()
		return queryset.filter(is_final=True)

class PublicationCreateView(AjaxableResponseMixin, CreateView):
	template_name = 'manager/publication/form.html'
	model = Publication
	fields = ['title', 'typology', 'subjects', 'authors', 'community',
			  'collection', 'publisher', 'address', 'year', 'reference',
			  'principal_language', 'principal_abstract', 'principal_keywords', 
			  'secondary_language', 'secondary_abstract', 'secondary_keywords', 
			  'issue_date', 'file']
	success_url = reverse_lazy('manager:publication_list')

	def form_valid(self, form):
		form.instance.is_final=True
		return super(PublicationCreateView, self).form_valid(form)

class PublicationUpdateView(UpdateView):
	template_name = 'manager/publication/form.html'
	model = Publication
	fields = ['title', 'typology', 'subjects', 'authors', 'community',
			  'collection', 'publisher', 'address', 'year', 'reference',
			  'principal_language', 'principal_abstract', 'principal_keywords', 
			  'secondary_language', 'secondary_abstract', 'secondary_keywords', 
			  'issue_date', 'file']
	success_url = reverse_lazy('manager:publication_list')
	
	def form_valid(self, form):
		form.instance.is_final=True
		return super(PublicationUpdateView, self).form_valid(form)

class PublicationDeleteView(DeleteView):
	template_name = 'manager/publication/check_delete.html'
	model = Publication
	success_url = reverse_lazy('manager:publication_list')

class PublicationDetailView(DetailView):
	template_name = 'manager/publication/detail.html'
	model = Publication

	def get(self, request, * args, ** kwargs):
		if not self.get_object().is_final:
			return HttpResponseRedirect(reverse_lazy('manager:publication_list'))
		return super(PublicationDetailView, self).get(request, * args, ** kwargs)

	def get_context_data(self, ** kwargs):
		context = super(PublicationDetailView, self).get_context_data( ** kwargs)
		return context

manager/templates/manager/community/_render.html
{% load i18n %}

<dl class="definition text" itemscope itemtype="http://schema.org/Community">
	<dt class="col-sm-2">{% trans "Name" %}:</dt>
	<dd class="col-sm-10" itemprop="name">{{ community.name }}</dd>

	<dt class="col-sm-2">{% trans "Collections" %}:</dt>
	<dd class="col-sm-10" itemprop="collections">
		{% for collection in page_obj %}
		<a href="{% url 'manager:collection_detail' slug=collection.slug %}" class="tag tag-primary">
			<i class="fa fa-community-group"></i>
			{{ collection }}
		</a>
		{% empty %}
			{% trans "Without Collection" %}
		{% endfor %}
		<div class="col-md-12">
		<div class="row">
		{% include "base/_paginate.html" %}
		</div>
		</div>
	</dd>

	<dt class="col-sm-2">{% trans "Publications" %}:</dt>
	<dd class="col-sm-10" itemprop="publications">
		<a href="{% url 'manager:community_publications' slug=community.slug %}" data-toggle="tooltip" title="{% trans "See Publications" %}">
			<i class="fa fa-book"></i>
			{% trans "See Publications" %}
		</a>
	</dd>

	<dt class="col-sm-2">{% trans "Registration date" %}:</dt>
	<dd class="col-sm-10" itemprop="registration_date">{{ community.registration_date }}</dd>
</dl>

manager/templates/manager/community/check_delete.html
{% extends "manager/community/list.html" %}


{% load i18n static %}

{% block title %}{% endblock %}

{% block stylesheet %}
{% endblock %}

{% block breadcrumbs %}
	{{ block.super }}
	<a href="{% url 'manager:community_delete' slug=object.slug %}" class="breadcrumb-item" >
		<i class="fa fa-remove"></i>
		{% trans "Confirm delete" %}
	</a>
{% endblock %}

{%  block page_title %}{% trans "Confirm delete" %}{% endblock %}

{% block content %}
	{% include 'base/_check_delete.html' %}
{% endblock %}

manager/templates/manager/community/detail.html
{% extends "manager/community/list.html" %}


{% load i18n static %}

{% block title %}{% endblock %}

{% block stylesheet %}
{% endblock %}

{% block breadcrumbs %}
	{{ block.super }}
	<a href="{% url 'manager:community_create' %}" class="breadcrumb-item" >
		<i class="fa fa-university"></i>
		{{ community.name }}
	</a>
{% endblock %}

{%  block page_title %}
	{{ community.name }}
	<div class="float-xs-right">
		{% if perms.manager.change_community %}
		<a href="{% url 'manager:community_update' slug=community.slug %}" class="btn btn-info" data-toggle="tooltip" title="{% trans "Edit" %}">
			<i class="fa fa-edit"></i>
		</a>
		{% endif %}
		{% if perms.manager.delete_community %}
		<a href="{% url 'manager:community_delete' slug=community.slug %}" class="btn btn-danger" data-toggle="tooltip" title="{% trans "Delete" %}">
			<i class="fa fa-remove"></i>
		</a>
		{% endif %}
	</div>
{% endblock %}

{% block content %}
	{% include 'manager/community/_render.html' %}
{% endblock %}

manager/templates/manager/community/form.html
{% extends "manager/community/list.html" %}


{% load i18n static %}

{% block title %}{% endblock %}

{% block stylesheet %}
{% endblock %}

{% block breadcrumbs %}
	{{ block.super }}
	<a href="{% url 'manager:community_create' %}" class="breadcrumb-item" >
		{% trans "Form Community" %}
	</a>
{% endblock %}

{% block page_title %}{% trans "Form Community" %}{% endblock %}

{% block content %}		
	{% include "base/_form.html" %}
{% endblock %}

manager/templates/manager/community/list.html
{% extends "manager/index.html" %}


{% load i18n static %}

{% block title %}{% endblock %}

{% block stylesheet %}
{% endblock %}

{% block communities %}active{% endblock %}

{% block breadcrumbs %}
	{{ block.super }}
	<a href="{% url 'manager:community_list' %}" class="breadcrumb-item" >
		<i class="fa fa-university"></i>
		{% trans "Communities" %}
	</a>
{% endblock %}

{%  block page_title %}{% trans "List of Communities" %}{% endblock %}

{% block content %}
	<div class="col-md-4">
	<div class="row">
	{% if perms.manager.add_community %}
		<a href="{% url 'manager:community_create' %}" class="btn btn-success">
			<i class="fa fa-plus"></i>
			{% trans "New Comunity" %}
		</a>
	{% endif %}
	</div>
	</div>

	<div class="col-md-8">
	<div class="row float-xs-right">
		{% include "base/_form_search.html" %}
	</div>
	</div>

	<table class="table table-bordered table-striped table-hover text">
		<thead class="thead-inverse">
			<tr>
				<th>{% trans "Name" %}</th>
				<th>{% trans "Publications" %}</th>
			</tr>
		</thead>

		<tbody>
			{% for community in object_list %}
				<tr>
					<td>
						<a href="{% url 'manager:community_detail' slug=community.slug %}">{{ community.name }}</a>
					</td>
					<td>
						<a href="{% url 'manager:community_publications' slug=community.slug %}"  data-toggle="tooltip" title="{% trans "See Publications" %}">
							<label>
								<i class="fa fa-book"></i>
								{% trans "See Publications" %}
							</label>
						</a>
					</td>
				</tr>
			{% empty %}
				<tr>
					<td class="text-xs-center">{% trans "No Community found!" %}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	{% include "base/_paginate.html" %}
{% endblock %}

manager/templates/manager/community/publications.html
{% extends "manager/publication/list.html" %}

{% load i18n static %}

{% block title %}{% endblock %}

{% block stylesheet %}
{% endblock %}

{% block communities %}active{% endblock %}
{% block publications %}{% endblock %}

{% block breadcrumbs %}
	<a href="{% url 'manager:home' %}" class="breadcrumb-item" >
		<i class="fa fa-home" aria-hidden="true"></i>
		{% trans "Home" %}
	</a>
	<a href="{% url 'manager:community_list' %}" class="breadcrumb-item" >
		<i class="fa fa-university"></i>
		{% trans "Communities" %}
	</a>
	<a href="{% url 'manager:community_publications' slug=community.slug %}" class="breadcrumb-item" >
		<i class="fa fa-book"></i>
		{% blocktrans with community=community %}
			Publications of {{ community }}
		{% endblocktrans %}
	</a>
{% endblock %}

{%  block page_title %}
	{% blocktrans with community=community %}
		Publications of {{ community }}
	{% endblocktrans %}
{% endblock %}